import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Footer from '@/components/common/Footer';
import Header from '@/components/common/Header';
import { ThemeProvider } from '@/components/providers/theme-provider';
import { SessionTimeoutModal } from '@/features/auth/presentation/organisms/SessionTimeoutModal';
import ServerSession from '@/app/session/server-session';
import { SessionProvider } from '@/context/SessionContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SessionProvider>
            <ServerSession>
              {(session) => (
                <div className="flex flex-col min-h-screen">
                  <Header />
                  <main>{children}</main>
                  <Footer />
                  <SessionTimeoutModal initialSession={session} />
                </div>
              )}
            </ServerSession>
          </SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
